language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "lts/*"
  - "node"

install:
  - npm install
script:
  - npm test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: echo "Deploying to npm"
      before_deploy:
        - npm run clean
        - npm run compile
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_AUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
